 -- ------------------------------------------------------------------------------------------------------------
-- Basic Analysis
 -- -------------------------------------------------------------------------------------------------------------
-- Q1.  How many post were made each year ?
-- Q2.  How many votes were made in each day of the week (Sun, Mon, Tue, etc.) ?
-- Q3.  List all comments created on September 19th, 2012.
-- Q4.  List all users under the age of 33, living in London.

-- -------------------------------------------------------------------------------------------------------------
-- Advanced Analysis
-- -------------------------------------------------------------------------------------------------------------
-- Q1.  Display the number of votes for each post title.
-- Q2.  Display posts with comments created by users living in the same location as the post creator
-- Q3.  How many users have never voted ?
-- Q4.  Display all posts having the highest amount of comments.
-- Q5.  For each post, how many votes are coming from users living in Canada ? What’s their percentage of the total number of votes ?
-- Q6.  How many hours in average, it takes to the first comment to be posted after a creation of a new post ?
-- Q7.  Whats the most common post tag ?
-- Q8.  Create a pivot table displaying how many posts were created for each year (Y axis) and each month (X axis).